src/NuGetGallery/Areas/Admin/Controllers/LuceneController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using NuGetGallery.Areas.Admin.Models;
using NuGetGallery.Configuration;
using NuGetGallery.Diagnostics;
using NuGetGallery.Infrastructure.Lucene;

namespace NuGetGallery.Areas.Admin.Controllers
{
    public partial class LuceneController : AdminControllerBase
    {
        protected IIndexingService IndexingService { get; set; }
        protected IAppConfiguration Config { get; set; }

        protected LuceneController() { }
        public LuceneController(IIndexingService indexingService, IAppConfiguration config)
        {
            IndexingService = indexingService;
            Config = config;
        }

        //
        // GET: /Admin/Lucene/

        public virtual async Task<ActionResult> Index()
        {
            return View("Index",
                await GetLuceneInfo());
        }

        private async Task<LuceneInfoModel> GetLuceneInfo()
        {
            var model = new LuceneInfoModel()
            {
                Directory = IndexingService.IndexPath,
                IsLocal = IndexingService.IsLocal,
                Location = Config.LuceneIndexLocation
            };

            try
            {
                model.LastUpdated = await IndexingService.GetLastWriteTime();
                model.DocumentCount = await IndexingService.GetDocumentCount();
                model.IndexSize = await IndexingService.GetIndexSizeInBytes();
                model.QueryStats = PerfCounters.GetStats(ExternalSearchService.SearchRoundtripTimePerfCounter);
            }
            catch (FileNotFoundException)
            {
                model.LastUpdated = null;
            }
            return model;
        }

        [HttpPost]
        public virtual Task<ActionResult> Rebuild()
        {
            IndexingService.UpdateIndex(forceRefresh: true);
            return Index();
        }

    }
}

src/NuGetGallery/Areas/Admin/Views/Lucene/Index.cshtml
@model NuGetGallery.Areas.Admin.Models.LuceneInfoModel
@{
    ViewBag.Title = "Lucene Maintainance";
    TimeZoneInfo timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById("Pacific Standard Time");
}

<h2>Lucene Maintainance</h2>

@if (Model.LastUpdated == null)
{
    <p>Lucene Index has not been built yet.</p>
}
else
{
    <p>
        Lucene Index was last rebuilt: <br />
        @Model.LastUpdated.Value.ToString("F") GMT<br />
        @TimeZoneInfo.ConvertTime(Model.LastUpdated.Value, TimeZoneInfo.Utc, timeZoneInfo).ToString("F") Pacific
    </p>
    <p>
        There are @Model.DocumentCount documents in the index.<br />
        The index consumes @Model.FormatIndexSize() of space.<br />
        The index is located on @Model.Directory
        @if(Model.IsLocal) {
            @:(@Model.Location)
        } 
        else 
        {
            @:(External)
        }
    </p>
}

@if(Model.IsLocal) 
{
    using (Html.BeginForm("Rebuild", "Lucene"))
    {
        <fieldset class="form">
            <input type="submit" value="Rebuild Now" />
            <p>NOTE: This will only affect the current instance!</p>
        </fieldset>
    }
}
else 
{
    <p>The Lucene Index is located on an external service and cannot be rebuilt.</p>
}

<h3>Query Statistics</h3>
@if (Model.QueryStats != null)
{
    <p>
        Average Round Trip Time: @Model.QueryStats.Average.ToString("0.00")ms<br/>
        Maximum Round Trip Time: @Model.QueryStats.Max.ToString("0.00")ms<br/>
        Minimum Round Trip Time: @Model.QueryStats.Min.ToString("0.00")ms<br/>
        Based on the most recent @Model.QueryStats.Samples samples<br/>
    </p>
}
else {
    <p>Query statistics are not available or no queries have been made since the last server restart</p>
}