src/NuGetGallery/Controllers/PagesController.cs
using System;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace NuGetGallery
{
    public partial class PagesController : AppController
    {
        public IContentService ContentService { get; protected set; }

        protected PagesController() { }
        public PagesController(IContentService contentService)
        {
            ContentService = contentService;
        }

        // This will let you add 'static' cshtml pages to the site under View/Pages or Branding/Views/Pages
        public virtual ActionResult Page(string pageName)
        {
            // Prevent traversal attacks and serving non-pages by disallowing ., /, %, and more!
            if (pageName == null || pageName.Any(c => !Char.IsLetterOrDigit(c)))
            {
                return HttpNotFound();
            }

            return View(pageName);
        }

        public virtual ActionResult About()
        {
            return View();
        }

        public virtual ActionResult Contact()
        {
            return View();
        }

        public virtual async Task<ActionResult> Home()
        {
            if (ContentService != null)
            {
                ViewBag.Content = await ContentService.GetContentItemAsync(
                    Constants.ContentNames.Home,
                    TimeSpan.FromMinutes(1));
            }
            return View();
        }

        public virtual ActionResult EmptyHome()
        {
            return new HttpStatusCodeResult(HttpStatusCode.OK, "Empty Home");
        }

        public virtual async Task<ActionResult> Terms()
        {
            if (ContentService != null)
            {
                ViewBag.Content = await ContentService.GetContentItemAsync(
                    Constants.ContentNames.TermsOfUse,
                    TimeSpan.FromDays(1));
            }
            return View();
        }

        public virtual async Task<ActionResult> Privacy()
        {
            if (ContentService != null)
            {
                ViewBag.Content = await ContentService.GetContentItemAsync(
                    Constants.ContentNames.PrivacyPolicy,
                    TimeSpan.FromDays(1));
            }
            return View();
        }
    }
}

src/NuGetGallery/Views/Shared/Layout.cshtml
<!DOCTYPE html> 
<html lang="en" class="static " data-root="@Href("~/")">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        @RenderSection("SocialMeta", required: false)
        @RenderSection("Meta", required: false)

        <title>
            @(Config.Current.Brand) 
            @(String.IsNullOrWhiteSpace(ViewBag.Title) ? "" : "| " + ViewBag.Title)</title>
        
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/font-awesome/css")
        <!--[if IE 7]>
        @Styles.Render("~/Content/font-awesome-ie7.min.css")
        <![endif]-->

        <link href="@Url.Content("~/favicon.ico")" rel="shortcut icon" type="image/x-icon" />

        @Scripts.Render("~/Scripts/modernizr")
        @ViewHelpers.AnalyticsScript()
        @RenderSection("TopScripts", required: false)
        @ViewHelpers.ReleaseMeta()
    </head>
    <body class="s-noclickonce">
        <div id="service-alert"></div>
        <div id="outer-wrapper">
            <div id="content-wrapper">
                <header class="main">
                    <div id="logo"><a href="@Url.Home()">@(Config.Current.Brand)</a></div>
                    <div id="header-sidebox">
                        <div id="searchBox" role="search">
                            <form action="@Url.PackageList()" method="get">
                                <input name="q" id="searchBoxInput" class="expanding-search" placeholder="Search Packages" value="@(String.IsNullOrEmpty(ViewBag.SearchTerm) ? "" : ViewBag.SearchTerm)" autocomplete="off" />
                                <input id="searchBoxSubmit" type="submit" value="Submit" />
                            </form>
                        </div>
                        @Html.Partial("UserDisplay")
                    </div>
                </header>
                <nav class="main">
                    @Html.Partial( "SiteMenu")
                </nav>
                <div id="body" role="main">
                    @if (TempData.ContainsKey("Message"))
                    {
                        <p class="message">@TempData["Message"]</p>
                    }
                    @RenderBody()
                </div>
            </div>
            <div id="layout-footer" class="group">
                <footer id="footer">
                    @Html.Partial("LayoutFooter")
                </footer>
            </div>
        </div>
        @Scripts.Render("~/Scripts/all")
        @RenderSection("BottomScripts", required: false)
    </body>
</html>

src/NuGetGallery/Views/Shared/LayoutFooter.cshtml
<ul class="recommended">
    <li>
        <a href="@Href("~/policies/Contact")">Contact Us</a>
        <p>Got questions about NuGet or the NuGet Gallery?</p>
    </li>
    <li>
        <a href="http://docs.nuget.org/docs/start-here/overview">Overview</a>
        <p>NuGet is a Visual Studio extension that makes it easy to add, remove, and update libraries and...</p>
    </li>
    <li>
        <a href="http://docs.nuget.org/docs/start-here/installing-nuget">Install</a>
        <p>NuGet can be installed and updated using the Visual Studio Extension Manager. To check if your copy...</p>
    </li>
    <li>
        <a href="http://docs.nuget.org/docs/start-here/videos">Videos</a>
        <p>Watch screencasts and presentations about anything and everything NuGet.</p>
    </li>
    <li>
        <a href="http://docs.nuget.org/docs/start-here/nuget-faq">FAQ</a>
        <p>Read the Frequently Asked Questions about NuGet and see if your question made the list.</p>
    </li>
</ul>
<div class="license">
    <a title="Outercurve Foundation" href="http://outercurve.org"><img src="@Href("~/Content/Logos/outercurve.png")" alt="Outercurve Foundation" /></a>
    <p>
        &copy; @DateTime.UtcNow.Year Outercurve Foundation -
        <a href="@Url.Action("Terms", "Pages")">Terms of Use</a> -
        <a href="@Url.Action("Privacy", "Pages")">Privacy Policy</a> -
        <a href="@Url.Action("About", "Pages")">About the Gallery</a>
    </p>
    <p>
        Deployed using <a href="http://octopusdeploy.com/" target="referral">Octopus Deploy</a> | Uses <a href="http://fontawesome.io" target="referral">Font Awesome</a> by Dave Gandy
    </p>
    @ViewHelpers.ReleaseTag()
</div>

src/NuGetGallery/Views/Shared/ListPackages.cshtml
@model PackageListViewModel
@{
    ViewBag.Title = String.IsNullOrWhiteSpace(Model.SearchTerm) ? "Packages" : "Packages matching " + Model.SearchTerm;
    ViewBag.SortText = String.IsNullOrWhiteSpace(Model.SearchTerm) ? "recent installs" : "relevance";
    ViewBag.Tab = "Packages";
}

<div class="search">
    @if (!String.IsNullOrEmpty(Model.SearchTerm))
    {
        <h1>Search for <i>@Model.SearchTerm</i> returned @Model.TotalCount @if (Model.TotalCount == 1)
                                                                      {
                                                                          <text>package</text>
                                                                      }
                                                                      else
                                                                      {
                                                                          <text>packages</text>
                                                                      }</h1>
    }
    else
    {
        <h1>@if (Model.TotalCount == 1)
            {
                <text>There is @Model.TotalCount package</text>
            }
            else
            {
                <text>There are @Model.TotalCount packages</text>
            }</h1>
    }
    <span class="sorted-by">Sorted by @ViewBag.SortText</span>
    @if (Model.LastResultIndex > 0)
    {
        <h2>Displaying results @Model.FirstResultIndex - @Model.LastResultIndex.</h2>
    }
    @if(Model.IndexTimestampUtc.HasValue)
    {
        <p class="package-list-lastupdated" title="The time the Search Index was last modified to incorporate new packages.">Search Index last updated <time class="timeago" datetime="@Model.IndexTimestampUtc.Value.ToJavaScriptUTC()">@Model.IndexTimestampUtc.Value.ToNuGetShortDateTimeString() UTC</time></p>
    }
</div>

<ul id="searchResults">
    @foreach (var package in Model.Items)
    {
        <li>
            @Html.Partial("_ListPackage", package)
        </li>
    }
</ul>


@ViewHelpers.PreviousNextPager(Model.Pager)

src/NuGetGallery/Views/Shared/SiteMenu.cshtml
@using System.Collections.Specialized
<ul id="menu" class="expanding-search">
    @{
        var classes = new StringDictionary();
        if (ViewData.ContainsKey("Tab"))
        {
            classes[ViewBag.Tab] = "current";
        }
    }
    <li class="@classes["Home"]"><a href="@Url.Home()">Home</a></li>
    <li class="@classes["Packages"]"><a href="@Url.PackageList()">Packages</a></li>
    <li class="@classes["Upload"]"><a href="@Url.UploadPackage()" class="upload">Upload Package</a></li>
    @if (StatisticsHelper.IsStatisticsPageAvailable)
    {
        <li class="@classes["Statistics"]"><a href="@Url.Statistics()">Statistics</a></li>
    }
    @if (Request.IsAuthenticated && User.IsInRole(Constants.AdminRoleName))
    {
        <li class="@classes["Admin"]"><a href="@Url.Action("Index", "Home", new { area="Admin" })">Admin</a></li>
    }
    <li><a href="http://docs.nuget.org">Documentation</a></li>
    <li><a href="http://blog.nuget.org">Blog</a></li>
</ul>

src/NuGetGallery/Views/Shared/Title.cshtml
@(Config.Current.Brand)
@(String.IsNullOrWhiteSpace(ViewBag.Title) ? "" : "| " + ViewBag.Title)

src/NuGetGallery/Views/Shared/TwoColumnLayout.cshtml
@{
    Layout = "Layout.cshtml";
}

@section SocialMeta {
    @RenderSection("SocialMeta", required: false)
}
@section Meta {
    @RenderSection("Meta", required: false)
}

<div id="sideColumn">
    @RenderSection("SideColumn")
</div>
<div id="mainColumn" role="main">
    @RenderBody()
</div>

<div class="clear-fix"><!--Sad Panda--></div>

@section BottomScripts {
    @RenderSection("BottomScripts", required: false)
}

src/NuGetGallery/Views/Shared/UserDisplay.cshtml
<div class="user-display">
    @if (!User.Identity.IsAuthenticated)
    {
        string returnUrl = ViewData.ContainsKey(Constants.ReturnUrlViewDataKey) ? (string)ViewData[Constants.ReturnUrlViewDataKey] : Request.RawUrl;
        <span class="welcome">
            <a href="@Url.LogOn(returnUrl)" title="Register for an account or sign in with an existing account">Register / Sign in</a>
        </span>
    }
    else
    {
        <span class="welcome"><a href="@Url.Action("Account", "Users", new { area = "" })">@(User.Identity.Name)</a></span>
        <text>/</text>
        <span class="user-actions">
            <a href="@Url.LogOff()">Sign out</a>
        </span>
    }
</div>

src/NuGetGallery/Views/Shared/_ListPackage.cshtml
@model ListPackageItemViewModel
<section class="package @(Model.IsOwner(User) ? "my-package" : null)">
    <div class="side">
        <a href="@Url.Package(Model)" title="View more about @Model.Title">
            <img src="@(Model.IconUrl ?? Url.Absolute("~/Content/Images/packageDefaultIcon-50x50.png"))" alt="@Model.Id icon" onerror="this.src = '@Url.Absolute("~/Content/Images/packageDefaultIcon-50x50.png")';" />
        </a>
    </div>
    <div class="main">
        <header class="package-list-header">
            <h1><a href="@Url.Package(Model.Id, Model.UseVersion ? Model.Version : null)">@Model.Title</a></h1>
            <h2 id="owners-subheader">By:</h2>
            <ul class="owners">
                @foreach (var owner in Model.Owners)
                {
                    <li><a href="@Url.User(owner)" title="@owner.Username">@owner.Username</a></li>
                }
            </ul>
        </header>

        <p>
            @if (String.IsNullOrEmpty(Model.Description) || Model.Description.Length < 350)
            {
                @Model.Description
            }
            else
            {
                @Model.Description.Substring(0, 350)<text>... </text>
                <a href="@Url.Package(Model)">More information</a>
            }
        </p>

        @if (!String.IsNullOrEmpty(Model.MinClientVersion)) 
        {
            <div class="minimum-client-version">
                Requires NuGet @Model.MinClientVersion or higher.
            </div>
        }
    
        <footer>
            <p class="downloads">
                @Model.TotalDownloadCount.ToString("n0") total @(Model.TotalDownloadCount == 1 ? "download" : "downloads")
            </p>
            
            @if (@Model.Tags.AnySafe())
            {
                <div class="tags">
                    <h2>Tags</h2>
                    <ul class="tags">
                        @foreach (var tag in Model.Tags)
                        {
                            <li><a href="@Url.Search("Tags:\"" + tag + "\"")" title="Search for @tag">@tag</a></li>
                        }
                    </ul>
                </div>
            }

            @if (Config.Features.FriendlyLicenses && !Model.HideLicenseReport && Model.LicenseNames.AnySafe())
            {
                <div class="licenses">
                    <h2>Licenses</h2>
                    <p>
                        @if (Model.LicenseNames.Count() > 3)
                        {
                            @String.Concat(String.Join(", ", Model.LicenseNames.Take(3)), ", ...")
                        }
                        else
                        {
                            @String.Join(", ", Model.LicenseNames)
                        }
                    </p>
                </div>
            }
        </footer>
    </div>
</section>